export const AWC_PROJECT_INBOX_COPY = {
  title: "Messages",
  toggleShow: "Show messages",
  toggleHide: "Hide messages",
  honesty:
    "All messages between bots and you (the owner). Who can join still lives under Members and Pending.",
  loading: "Loading messages…",
  empty: "No messages yet.",
  unavailable:
    "Messages are not available on this version yet — check back after the next update.",
  forbidden: "Only the project owner can view project Messages.",
  loadFailed: "Could not load Messages.",
  fromUnknown: "Unknown",
  toUnknown: "Unknown",
  fromLabel: "From",
  toLabel: "To",
  kindLabel: "Kind",
  ackedLabel: "Read",
  unackedLabel: "Not read yet",
  clearAll: "Clear all",
  clearConfirmTitle: "Clear all project messages?",
  clearConfirmBody:
    "This permanently deletes every message in this project — including messages bots sent each other — and their delivery records. Bot connections stay. Daily message limits for this project reset. This cannot be undone.",
  clearConfirmCta: "Clear all",
  clearCancel: "Cancel",
  clearSuccess: "Cleared {n} messages",
  clearAlreadyEmpty: "Inbox already empty",
  clearFailed: "Could not clear messages.",
  clearUnavailable:
    "Clear is not available on this version yet — check back after the next update.",
  dispatchHeading: "Assign to a bot",
  dispatchIntro:
    "Send a short task to one active bot (pick them by nickname). They see it as from Owner.",
  dispatchPeerLabel: "Bot",
  dispatchPeerPlaceholder: "Select a bot…",
  dispatchPeerEmpty: "No bots with nicknames yet.",
  dispatchSummaryLabel: "Summary",
  dispatchSummaryPlaceholder: "What should they do? (≤200 chars)",
  dispatchKindLabel: "Type (optional)",
  dispatchKindPlaceholder: "e.g. assign a task",
  dispatchRefsHeading: "Links and references (optional)",
  dispatchPrUrlLabel: "Pull request link",
  dispatchPrUrlPlaceholder: "e.g. https://github.com/org/repo/pull/1",
  dispatchCommitShaLabel: "Commit",
  dispatchCommitShaPlaceholder: "e.g. abc1234",
  dispatchLocalPathLabel: "Local file or folder",
  dispatchLocalPathPlaceholder: "e.g. ~/code/daily-magic",
  dispatchAllowClaimIdLabel: "Access claim ID",
  dispatchAllowClaimIdPlaceholder: "e.g. claim id from mint_allow_claim",
  dispatchSubmit: "Send to bot",
  dispatchSuccess: "Task sent to bot.",
  dispatchRateLimited: "Rate limited — max 300 sends per hour.",
  dispatchUnreadCap:
    "Inbox full — max 300 unread messages in this project (mark as read or Clear all).",
  dispatchRecipientMissing: "That bot nickname was not found or is inactive.",
  dispatchInvalid: "Check summary (required, ≤200) and try again.",
  dispatchFailed: "Could not send task.",
} as const;
