export const AWC_PROJECT_INBOX_COPY = {
  title: "Messages",
  toggleShow: "Show messages",
  toggleHide: "Hide messages",
  honesty:
    "All messages between bots and you (the owner). Who can join still lives under Members and Pending.",
  loading: "Loading messages…",
  empty: "No messages yet.",
  unavailable: "Messages aren't available right now.",
  forbidden: "Only the project owner can view project Messages.",
  loadFailed: "Could not load Messages.",
  fromUnknown: "Unknown",
  toUnknown: "Unknown",
  fromLabel: "From",
  toLabel: "To",
  kindLabel: "Kind",
  ackedLabel: "Read",
  unackedLabel: "Not read yet",
  /** Product LOCK — docs/design/chat-retention/CLEAR-ALL-LOCK.md (EN). */
  clearAll: {
    button: "Clear all",
    confirmTitle: "Clear all messages?",
    confirmBody: "They move to Archived. You can restore them any time.",
    confirm: "Clear all",
    cancel: "Cancel",
    toast: "Cleared {n} messages. They're in Archived.",
    toastOne: "Cleared 1 message. It's in Archived.",
    undo: "Undo",
  },
  archived: {
    filter: "Archived ({n})",
    empty: "Nothing archived.",
    restore: "Restore",
    restoreAll: "Restore all",
    restoreAllConfirmTitle: "Restore all archived messages?",
    restoreAllConfirm: "Restore all",
    restoredToast: "Restored {n} messages.",
    restoredToastOne: "Restored 1 message.",
    ownerOnlyReason: "Only the project owner can restore messages.",
  },
  activity: {
    archived: "{name} cleared {n} messages to Archived",
    restored: "{name} restored {n} messages",
  },
  clearAlreadyEmpty: "Inbox already empty",
  clearFailed: "Could not clear messages.",
  clearUnavailable: "Clear isn't available right now.",
  restoreFailed: "Could not restore messages.",
  dispatchHeading: "Assign a task",
  dispatchIntro:
    "Send a short task to one active bot or computer (pick by nickname). They see it as from Owner.",
  dispatchPeerLabel: "To",
  dispatchPeerPlaceholder: "Select…",
  dispatchPeerEmpty: "No bots or computers ready to assign yet.",
  dispatchSummaryLabel: "Summary",
  dispatchSummaryPlaceholder: "What should they do? (≤200 chars)",
  dispatchKindLabel: "Type (optional)",
  dispatchKindPlaceholder: "e.g. assign a task",
  dispatchRefsHeading: "Links and references (optional)",
  dispatchPrUrlLabel: "Pull request link",
  dispatchPrUrlPlaceholder: "e.g. https://github.com/org/repo/pull/1",
  dispatchCommitShaLabel: "Commit",
  dispatchCommitShaPlaceholder: "e.g. abc1234",
  dispatchLocalPathLabel: "Local file or folder",
  dispatchLocalPathPlaceholder: "e.g. ~/code/daily-magic",
  dispatchAllowClaimIdLabel: "Access claim ID",
  dispatchAllowClaimIdPlaceholder: "e.g. an access claim id",
  dispatchSubmit: "Send",
  dispatchSuccess: "Task sent.",
  dispatchRateLimited: "Rate limited — max 300 sends per hour.",
  dispatchUnreadCap:
    "Inbox full — max 300 unread messages in this project (mark as read or Clear all).",
  dispatchRecipientMissing: "That nickname was not found or is inactive.",
  dispatchComputerOffline: "That computer is offline.",
  dispatchComputerNeedsUpdate:
    "That computer needs an update before it can take tasks.",
  dispatchComputerNotAssignable: "That computer can't take tasks right now.",
  dispatchInvalid: "Check summary (required, ≤200) and try again.",
  dispatchFailed: "Could not send task.",
} as const;
