/** One-window Activity feed / gate EN (brief + EN-PASS). */
export const ONE_WINDOW_FEED_COPY = {
  emptyTitle: "No messages yet",
  emptyBody: "Say hello or @ an assistant to assign work.",
  emptyNeedsTitle: "Nothing needs you",
  emptyNeedsBody: "Tasks waiting on you and approvals to decide show up here.",
  emptyApprovalsTitle: "No approvals waiting",
  emptyApprovalsBody: "Join requests and run approvals show up here.",
  loading: "Loading messages",
  errorTitle: "Messages didn't load",
  errorBody:
    "We couldn't reach AgentWitch. Check your connection, then try again. Nothing you sent was lost.",
  tryAgain: "Try again",
  projectRequiredTitle: "Pick a project",
  projectRequired:
    "Pick a project first. Every message and task belongs to a project.",
  filterAll: "All",
  filterNeedsYou: "Needs you",
  filterApprovals: "Approvals",
  betweenAssistants: "Between assistants",
  /** DF-023 filter toggle (owner): show/hide bot↔bot lines. Default shown. */
  showBetweenAssistants: "Show between assistants",
  hideBetweenAssistants: "Hide between assistants",
  kindTask: "Task",
  openTask: "Open task",
  newMark: "New",
  accessDeepLink: "Open Access",
  approve: "Approve",
  deny: "Deny",
  approvalRunKind: "Approval · Run on a computer",
  approvalJoinKind: "Approval · Join request",
  approvalKind: "Approval",
  waitingForYou: "Waiting for you",
  timedOut: "Timed out",
  approved: "Approved",
  denied: "Denied",
  approvalTip:
    "This is the same request you see in Access. Deciding here updates it there too.",
  rowWantsTo: "Wants to",
  rowRequest: "Request",
  rowTime: "Time",
  rowEmail: "Email",
  approvedBy: "Approved by you at {time}.",
  deniedBy: "Denied by you at {time}.",
  runApprovedAfter: "It is running now.",
  runDeniedAfter: "Nothing ran.",
  joinApprovedAfter: "They can now open the project.",
  joinDeniedAfter: "They were told the request was declined.",
  askAgain: "Ask {name} again",
  noticeArchivedOne: "1 older message is archived. It is kept, not deleted.",
  noticeArchivedMany:
    "{n} older messages are archived. They are kept, not deleted.",
  noticeRestore: "Restore",
  noticeQuiet:
    "{name} has been quiet for a while. It may be busy, or its computer may be asleep.",
  betweenTo: "to",
  dayToday: "Today · {date}",
  dayYesterday: "Yesterday · {date}",
  jumpNewOne: "1 new",
  jumpNewMany: "{n} new",
  jumpNewA11y: "Jump to the first new message",
  accessPending: "Access · {n} pending",
  accessPendingA11y: "Open Access: {n} pending",
} as const;
