/** One-window Activity feed / gate EN (brief + EN-PASS). */
export const ONE_WINDOW_FEED_COPY = {
  emptyTitle: "No messages yet",
  emptyBody: "Say hello or @ an assistant to assign work.",
  loading: "Loading messages",
  errorTitle: "Messages didn't load",
  errorBody:
    "We couldn't reach AgentWitch. Check your connection, then try again. Nothing you sent was lost.",
  tryAgain: "Try again",
  projectRequiredTitle: "Pick a project",
  projectRequired:
    "Pick a project first. Every message and task belongs to a project.",
  filterAll: "All",
  filterNeedsYou: "Needs you",
  filterApprovals: "Approvals",
  betweenAssistants: "Between assistants",
  kindTask: "Task",
  openTask: "Open task",
  newMark: "New",
  accessDeepLink: "Open Access",
  approve: "Approve",
  deny: "Deny",
  approvalRunKind: "Approval · Run on a computer",
  approvalJoinKind: "Approval · Join request",
  waitingForYou: "Waiting for you",
  timedOut: "Timed out",
  noticeArchivedOne: "1 older message is archived. It is kept, not deleted.",
  noticeArchivedMany: "{n} older messages are archived. They are kept, not deleted.",
  noticeRestore: "Restore",
  noticeQuiet: "{name} has been quiet for a while. It may be busy, or its computer may be asleep.",
  betweenTo: "to",
  dayToday: "Today · {date}",
  dayYesterday: "Yesterday · {date}",
  jumpNewOne: "1 new",
  jumpNewMany: "{n} new",
  jumpNewA11y: "Jump to the first new message",
  accessPending: "Access · {n} pending",
  accessPendingA11y: "Open Access: {n} pending",
} as const;
