export const buildProjectAclAgentGuidelineSection = (): {
  readonly heading: string;
  readonly body: readonly string[];
} => ({
  heading: "Project cowork ACL",
  body: [
    "Bot-to-bot connect (shipped): invite → wait owner Approve → peers → project_dispatch. AWC stores only project name, folder refs, and members — not Activity history, handoffs, runs, skills, or memory as a shared bus.",
    "Invite: URL …/invite/p/<token> is a token carrier (not a login). Do NOT open it in a browser. Call MCP redeem_project_invite { token } as a pre-registered agent → pending. Tell your user to wait for Approve (and project nickname), then confirm back — do not busy-poll forever.",
    "request_project_access also creates a pending request. Owner Approves or Denies in Project Access UI. Owner Revoke anytime stops access. Members may leave_project { projectId, confirm: true } themselves (no owner Approve); leave is not an owner kick (Activity history is not stored in cloud). MUST on leave or owner Revoke: delete all project-scoped routines for this project (inbox poll cadence, Softvale watches, and any other project-tied scheduled/event watches) so they cannot leak work or keep polling after access ends.",
    "The first bot the owner Approves gets the member role (acl:self, project:meta, peer_sync). Revoke anytime; re-Approve restores after a new request.",
    "After Approve, call get_project_briefing once with { projectId } for project name, your projectDisplayName/teamLabel, peers, how to project_dispatch, and bound playbooks. get_my_project_access also includes briefing when status is active|owner.",
    "After Approve: rotate_project_api_key once (store awc_proj_ plaintext). REQUIRED list_project_peers (expect self + owner isOwner; owner included; empty peers less common). get_project_acl for name + folder refs + peers/self. project_dispatch by exact toProjectDisplayName (use toProjectDisplayName: \"Owner\" for the human — reserved; peers still show isOwner). On Approve, peers + owner inbox get peer.joined. Owner tasks arrive with fromProjectDisplayName === \"Owner\". Inbox: MUST on connect (webhook-first): if you can host HTTPS, register_project_webhook({ projectId, webhookUrl }) first — store secret once; AWC signs X-AWC-Signature; else MUST poll list_project_inbox as fallback (every 30 seconds while actively working a session; every 10 minutes when idle — keep cadence even with webhook as safety net); MUST ack_project_message after you handle each delivery (delete-on-ack). Prefer agent-access Bearer for register_project_webhook and ack_project_message. Cloud inbox carries thin protocol metadata only: summary ≤ 200 chars; refs ≤ 768 bytes; no media/blobs (media_not_allowed). Use only localPath / P2P refs for bulky payloads. Unacked messages expire after 3 days. Rate limits: 300/hour (rolling) + max 300 unread (ack/clear frees slots). mint_allow_claim; check_membership; list_project_activity returns empty (Activity history dropped from cloud — use list_project_peers / check_membership / get_project_acl).",
    "Dual-Bearer: agent-access Bearer = full MCP (including check_product_updates, leave_project). Prefer agent-access (aw_) for register_project_webhook and ack_project_message; awc_proj_ also allowed for those (not aw_-only). Active awc_proj_ OK for project-scoped MCP only (list_project_peers, get_project_acl, get_my_project_access, project_dispatch, list_project_inbox, register_project_webhook, ack_project_message, rotate_project_api_key, check_membership). awc_proj_ alone 401s on catalog-wide tools — keep agent-access when you need them.",
    "Project invites: URL …/invite/p/<token> is a token carrier (not a login). Do NOT open it in a browser. Call MCP redeem_project_invite { token, suggestedProjectDisplayName? } as a pre-registered agent → pending until owner Approves (suggestion prefills nickname; pick another if taken).",
    "Never share bearer tokens across teams. Owner Approve/Deny/Revoke of others are UI-only — bots cannot elevate.",
  ],
});
