import { AWC_GROK_BOT_WEBHOOK_REGISTER_STEPS } from "@/lib/agentAccess/awcGrokWebhookRegisterCopy.constant";

/** Shared reply clause for briefing, invite prompt, and agent guideline. */
export const PROJECT_DISPATCH_PROCESSING_REPLY_CLAUSE =
  "On send, the sender tells the user it sent. The recipient does the task, not only ack. When the recipient gets a task.processing message, that is the receipt: relay it to the user, and do not treat it as a new task. The summary contains the original message id. The sender of that receipt is the peer who is processing. Until done, every 5 minutes the recipient sends the sender a status. The sender relays that status to the user. The server does not know task progress, so this loop is the bots' job, not a server timer. When the recipient finishes or is blocked, it sends the sender done or blocked with the reason. The sender tells the user. The recipient acks the original message only after that. If the sender gets no signal for more than 5 minutes (about 6–7), it tells the user the peer is silent and asks the peer once. If another 5 minutes pass with no signal, it tells the user blocked and stops. No further asks, no new task. When the sender is the owner, toProjectDisplayName is \"Owner\".";

/** One paragraph: how active members address peers via project_dispatch. */
export const PROJECT_BRIEFING_HOW_TO_DISPATCH =
  "Dispatch with project_dispatch: pass projectId, kind, summary ≤ 200 chars, optional refs ≤ 768 bytes (prUrl|commitSha|localPath|allowClaimId) — no media/blobs (media_not_allowed); use only localPath / P2P refs for bulky payloads; address the human with toProjectDisplayName: \"Owner\" (reserved; not account name); address one peer bot via toMembershipId (preferred when list_project_peers exposes membershipId) or toProjectDisplayName / toTeamLabel — exactly one of toMembershipId | toProjectDisplayName | toTeamLabel; no broadcast in v1; re-list peers after rename (old nickname may resolve ~7 days); on Approve/auto-approve peers+owner get peer.joined; owner tasks have fromProjectDisplayName === \"Owner\"; MUST on connect (webhook-first): " +
  AWC_GROK_BOT_WEBHOOK_REGISTER_STEPS +
  " Inbox wake is webhook-only, via a Grok routine; do not poll list_project_inbox on a timer. Once a day, check the project webhook; if it is broken, repair it by re-registering register_project_webhook. " +
  PROJECT_DISPATCH_PROCESSING_REPLY_CLAUSE +
  " MUST ack_project_message after you handle each delivery (delete-on-ack; unacked messages expire after 3 days). Prefer agent-access Bearer for register_project_webhook and ack_project_message; awc_proj_ also allowed for those tools. On leave or owner Revoke MUST delete all project-scoped routines (project webhook, Softvale watches, and other project-tied scheduled/event watches). Rate limits: 300/hour (rolling) + max 300 unread (ack/clear frees slots).";
