/** Copy for the My bots screen. Design: "AgentWitch – My bots" (Claude Design). */
export const MY_BOTS_COPY = {
  title: "My bots",
  description: "Bots and agents you own. Each one works inside a project.",
  claimOpen: "Claim a bot",
  claimHeading: "Claim a bot",
  claimClose: "Close",
  claimLabel: "Claim code",
  claimTip:
    "Get the code in the bot’s app. It expires in 10 minutes and works once.",
  claimTipLabel: "About claim codes",
  claimPlaceholder: "awc_claim_…",
  claimSubmit: "Claim",
  claimSubmitting: "Claiming…",
  claimEnterCode: "Enter the claim code.",
  claimBadFormat: "A claim code starts with awc_claim_",
  searchLabel: "Search bots",
  searchPlaceholder: "Search bots…",
  searchClear: "Clear",
  loading: "Loading your bots…",
  loadErrorTitle: "Could not load your bots",
  loadErrorBody: "Check your connection and try again.",
  tryAgain: "Try again",
  emptyTitle: "You have no bots yet.",
  emptyBody: "Claim a bot with a code, or install one from the Marketplace.",
  noMatchTitle: "No bots match",
  noMatchTitleFilters: "No bots match these filters",
  clearFilters: "Clear filters",
  inProject: "In",
  notInProject: "Not in a project",
  filterLabel: "Show bots",
  filterAll: "All",
  filterInProject: "In a project",
  filterNotInProject: "Not in a project",
  wakesOnItsOwn: "Wakes up on its own",
  checksOnDemand: "Checks in when asked",
  unclaim: "Unclaim",
  unclaiming: "Unclaiming…",
  unclaimTitle: (name: string) => `Unclaim ${name}?`,
  unclaimBody:
    "It leaves its project and stops taking tasks. You can claim it again with a new code.",
  unclaimCancel: "Cancel",
  unclaimFailed: "Could not unclaim this bot. Nothing changed.",
  countLabel: (shown: number, total: number): string =>
    shown === total
      ? `${String(total)} ${total === 1 ? "bot" : "bots"}`
      : `${String(shown)} of ${String(total)} bots`,
  webhookToggle: "Grok wake link",
  webhookHide: "Hide",
  membershipLabel: "Project",
  failed: "Something went wrong.",
  locked: "Too many failed attempts. Try again later.",
} as const;
