export const INCIDENT_POSTMORTEM_EXAMPLE_REQUEST = [
  "Draft a blameless incident postmortem from the workflow form fields.",
  "",
  "## Timeline and impact",
  "Read timeline and impact from the workflow form.",
  "Write an executive impact summary first, then a chronological timeline (detection → mitigation → resolution).",
  "Use timestamps when the operator provided them; mark unknown times as approximate.",
  "Summarize gaps or contradictions in [[PROGRESS]]; the operator will answer at the next checkpoint.",
  "Do not finalize root cause or action items in this step.",
  "",
  "## Root cause and action items",
  "Continue from prior operator answers (see checkpoint responses above).",
  "Read rootCause and followUps from the workflow form.",
  "State root cause as a hypothesis with evidence; stay blameless and systems-focused.",
  "Merge impact, timeline, root cause, and follow-ups into one postmortem document.",
  "Separate immediate mitigations from long-term preventive actions; note owners when given.",
  "Call out monitoring or runbook gaps if implied.",
  "Stop before final operator review — the workflow will pause for approval.",
].join("\n");
