/* eslint-disable -- generated by scripts/generateStorybookPageStories.ts */
import { awcPageStories } from "@/utils/storybook/stories/awcPageStories.shared";

export default {
  title: "AWC/Pages",
  parameters: { layout: "fullscreen" },
};

export const home_marketing_ready = awcPageStories.home_marketing_ready;
export const login_ready = awcPageStories.login_ready;
export const for_agents_ready = awcPageStories.for_agents_ready;
export const setup_writer_ready = awcPageStories.setup_writer_ready;
export const privacy_ready = awcPageStories.privacy_ready;
export const terms_ready = awcPageStories.terms_ready;
export const home_signed_in_loading = awcPageStories.home_signed_in_loading;
export const home_signed_in_empty = awcPageStories.home_signed_in_empty;
export const home_signed_in_error = awcPageStories.home_signed_in_error;
export const home_signed_in_ready = awcPageStories.home_signed_in_ready;
export const projects_loading = awcPageStories.projects_loading;
export const projects_empty = awcPageStories.projects_empty;
export const projects_error = awcPageStories.projects_error;
export const projects_ready = awcPageStories.projects_ready;
export const project_detail_loading = awcPageStories.project_detail_loading;
export const project_detail_empty = awcPageStories.project_detail_empty;
export const project_detail_error = awcPageStories.project_detail_error;
export const project_detail_ready = awcPageStories.project_detail_ready;
export const library_loading = awcPageStories.library_loading;
export const library_guest = awcPageStories.library_guest;
export const library_empty = awcPageStories.library_empty;
export const library_error = awcPageStories.library_error;
export const library_ready = awcPageStories.library_ready;
export const marketplace_loading = awcPageStories.marketplace_loading;
export const marketplace_guest = awcPageStories.marketplace_guest;
export const marketplace_empty = awcPageStories.marketplace_empty;
export const marketplace_error = awcPageStories.marketplace_error;
export const marketplace_ready = awcPageStories.marketplace_ready;
export const reports_loading = awcPageStories.reports_loading;
export const reports_guest = awcPageStories.reports_guest;
export const reports_empty = awcPageStories.reports_empty;
export const reports_error = awcPageStories.reports_error;
export const reports_ready = awcPageStories.reports_ready;
export const report_detail_loading = awcPageStories.report_detail_loading;
export const report_detail_empty = awcPageStories.report_detail_empty;
export const report_detail_error = awcPageStories.report_detail_error;
export const report_detail_ready = awcPageStories.report_detail_ready;
export const automations_loading = awcPageStories.automations_loading;
export const automations_empty = awcPageStories.automations_empty;
export const automations_error = awcPageStories.automations_error;
export const automations_ready = awcPageStories.automations_ready;
export const prompt_optimizer_ready = awcPageStories.prompt_optimizer_ready;
export const prompt_optimizer_guide_ready =
  awcPageStories.prompt_optimizer_guide_ready;
export const connection_lab_ready = awcPageStories.connection_lab_ready;
export const connection_lab_error = awcPageStories.connection_lab_error;
export const showcases_ready = awcPageStories.showcases_ready;
export const admin_users_ready = awcPageStories.admin_users_ready;
export const admin_users_empty = awcPageStories.admin_users_empty;
export const admin_groups_ready = awcPageStories.admin_groups_ready;
export const admin_groups_empty = awcPageStories.admin_groups_empty;
export const admin_groups_error = awcPageStories.admin_groups_error;
