/* eslint-disable -- generated by scripts/generateStorybookPageStories.ts */
import { awlDiagnosticsPageStories } from "@/utils/storybook/stories/awlDiagnosticsPageStories.shared";

export default {
  title: "AWL/Pages/Diagnostics",
  parameters: { layout: "fullscreen" },
};

export const knowledge_ready = awlDiagnosticsPageStories.knowledge_ready;
export const knowledge_empty = awlDiagnosticsPageStories.knowledge_empty;
export const history_ready = awlDiagnosticsPageStories.history_ready;
export const history_empty = awlDiagnosticsPageStories.history_empty;
export const errors_ready = awlDiagnosticsPageStories.errors_ready;
export const errors_empty = awlDiagnosticsPageStories.errors_empty;
export const errors_error = awlDiagnosticsPageStories.errors_error;
export const traffic_ready = awlDiagnosticsPageStories.traffic_ready;
export const traffic_empty = awlDiagnosticsPageStories.traffic_empty;
