/* eslint-disable -- generated by scripts/generateStorybookPageStories.ts */
import { awlStatusWriterPageStories } from "@/utils/storybook/stories/awlStatusWriterPageStories.shared";

export default {
  title: "AWL/Pages/Status & writer",
  parameters: { layout: "fullscreen" },
};

export const status_ready = awlStatusWriterPageStories.status_ready;
export const status_empty = awlStatusWriterPageStories.status_empty;
export const status_error = awlStatusWriterPageStories.status_error;
export const writer_api_ready = awlStatusWriterPageStories.writer_api_ready;
export const writer_api_error = awlStatusWriterPageStories.writer_api_error;
export const writer_sessions_ready =
  awlStatusWriterPageStories.writer_sessions_ready;
export const writer_sessions_empty =
  awlStatusWriterPageStories.writer_sessions_empty;
