/* eslint-disable -- generated by scripts/generateStorybookPageStories.ts */
import { awlHomeTaskPageStories } from "@/utils/storybook/stories/awlHomeTaskPageStories.shared";

export default {
  title: "AWL/Pages/Home & task",
  parameters: { layout: "fullscreen" },
};

export const home_ready = awlHomeTaskPageStories.home_ready;
export const home_empty = awlHomeTaskPageStories.home_empty;
export const home_error = awlHomeTaskPageStories.home_error;
export const task_ready = awlHomeTaskPageStories.task_ready;
export const task_empty = awlHomeTaskPageStories.task_empty;
export const task_error = awlHomeTaskPageStories.task_error;
