/* eslint-disable -- generated by scripts/generateStorybookPageStories.ts */
import { awlPageStories } from "@/utils/storybook/stories/awlPageStories.shared";

export default {
  title: "AWL/Pages",
  parameters: { layout: "fullscreen" },
};

export const home_ready = awlPageStories.home_ready;
export const home_empty = awlPageStories.home_empty;
export const home_error = awlPageStories.home_error;
export const task_ready = awlPageStories.task_ready;
export const task_empty = awlPageStories.task_empty;
export const task_error = awlPageStories.task_error;
export const prompt_optimizer_ready = awlPageStories.prompt_optimizer_ready;
export const prompt_optimizer_empty = awlPageStories.prompt_optimizer_empty;
export const prompt_optimizer_error = awlPageStories.prompt_optimizer_error;
export const prompt_optimizer_loading = awlPageStories.prompt_optimizer_loading;
export const prompt_optimizer_guide_ready =
  awlPageStories.prompt_optimizer_guide_ready;
export const status_ready = awlPageStories.status_ready;
export const status_empty = awlPageStories.status_empty;
export const status_error = awlPageStories.status_error;
export const projects_ready = awlPageStories.projects_ready;
export const projects_empty = awlPageStories.projects_empty;
export const projects_error = awlPageStories.projects_error;
export const project_ready = awlPageStories.project_ready;
export const project_empty = awlPageStories.project_empty;
export const project_error = awlPageStories.project_error;
export const harness_ready = awlPageStories.harness_ready;
export const harness_empty = awlPageStories.harness_empty;
export const harness_error = awlPageStories.harness_error;
export const writer_api_ready = awlPageStories.writer_api_ready;
export const writer_api_error = awlPageStories.writer_api_error;
export const knowledge_ready = awlPageStories.knowledge_ready;
export const knowledge_empty = awlPageStories.knowledge_empty;
export const history_ready = awlPageStories.history_ready;
export const history_empty = awlPageStories.history_empty;
export const writer_sessions_ready = awlPageStories.writer_sessions_ready;
export const writer_sessions_empty = awlPageStories.writer_sessions_empty;
export const errors_ready = awlPageStories.errors_ready;
export const errors_empty = awlPageStories.errors_empty;
export const errors_error = awlPageStories.errors_error;
export const traffic_ready = awlPageStories.traffic_ready;
export const traffic_empty = awlPageStories.traffic_empty;
