/* eslint-disable -- generated by scripts/generateStorybookPageStories.ts */
import { awlPromptOptimizerPageStories } from "@/utils/storybook/stories/awlPromptOptimizerPageStories.shared";

export default {
  title: "AWL/Prompt optimizer",
  parameters: { layout: "fullscreen" },
};

export const prompt_optimizer_ready =
  awlPromptOptimizerPageStories.prompt_optimizer_ready;
export const prompt_optimizer_empty =
  awlPromptOptimizerPageStories.prompt_optimizer_empty;
export const prompt_optimizer_error =
  awlPromptOptimizerPageStories.prompt_optimizer_error;
export const prompt_optimizer_loading =
  awlPromptOptimizerPageStories.prompt_optimizer_loading;
export const prompt_optimizer_guide_ready =
  awlPromptOptimizerPageStories.prompt_optimizer_guide_ready;
