/* eslint-disable -- generated by scripts/generateStorybookPageStories.ts */
import { awlProjectsHarnessPageStories } from "@/utils/storybook/stories/awlProjectsHarnessPageStories.shared";

export default {
  title: "AWL/Pages/Projects & harness",
  parameters: { layout: "fullscreen" },
};

export const projects_ready = awlProjectsHarnessPageStories.projects_ready;
export const projects_empty = awlProjectsHarnessPageStories.projects_empty;
export const projects_error = awlProjectsHarnessPageStories.projects_error;
export const project_ready = awlProjectsHarnessPageStories.project_ready;
export const project_empty = awlProjectsHarnessPageStories.project_empty;
export const project_error = awlProjectsHarnessPageStories.project_error;
export const harness_ready = awlProjectsHarnessPageStories.harness_ready;
export const harness_empty = awlProjectsHarnessPageStories.harness_empty;
export const harness_error = awlProjectsHarnessPageStories.harness_error;
