/** Account notifications tab EN. */
export const ACCOUNT_NOTIFY_COPY = {
  h2: "What we tell you",
  tip: "Choose email and in-app notes for each event. Changes save as you go.",
  colEvent: "Event",
  colEmail: "Email",
  colInApp: "In app",
  sendTest: "Send a test email",
  testSent: "Test email sent",
  rowTask: "A task finishes",
  rowTaskHint: "A short note when an assistant finishes a task.",
  rowApproval: "An assistant needs your approval",
  rowApprovalHint: "When a rule or automation says to ask first.",
  rowDigest: "Weekly digest",
  rowDigestHint: "Mondays at 09:00. What your assistants did last week.",
  rowInvites: "Invites and access requests",
  rowInvitesHint: "When someone invites you or asks to join your project.",
  rowBilling: "Billing and trial reminders",
  rowBillingHint: "Receipts, failed payments and when your trial ends.",
  billingLocked: "Billing emails cannot be turned off.",
  quietH2: "Quiet hours",
  quietTip:
    "No emails or in-app notes during these hours. Approvals wait until quiet hours end.",
  quietFrom: "From",
  quietTo: "To",
  quietOn: "Quiet from {from} to {to} ({tz}).",
  quietOff: "Quiet hours are off.",
  quietSame: "From and To must be different.",
  prefsLocalNote: "Notification prefs save on this device only for now.",
} as const;
