export const PROJECT_SKILLS_COPY = {
  title: "Skills",
  hint: "Playbooks shared with this project. Members see published skills; drafts stay with you and the owner. Text up to 64KB, last 20 versions kept.",
  loading: "Loading skills…",
  empty: "No skills shared yet.",
  publishHeading: "Share a skill",
  nameLabel: "Name",
  descriptionLabel: "Short description (optional)",
  bodyLabel: "Skill text",
  publish: "Publish",
  saveDraft: "Save draft",
  publishDraft: "Publish draft",
  publishing: "Saving…",
  revoke: "Revoke",
  revoking: "Revoking…",
  draftBadge: "Draft",
  versionLabel: (version: number) => `v${version}`,
  bytesLabel: (bytes: number, max: number) =>
    `${Math.ceil(bytes / 1024)} / ${Math.round(max / 1024)} KB`,
  tooLarge: "Skill text is over 64KB.",
  published: "Skill published.",
  draftSaved: "Draft saved.",
  revoked: "Skill revoked.",
} as const;
