export const PROJECT_SKILLS_COPY = {
  title: "Skills & playbooks",
  hint: "Skills and playbooks shared with this project. Members and viewers see published skills. Drafts stay with the owner. Each skill can be up to 64 KB of text, and the last 20 versions are kept.",
  loading: "Loading skills…",
  empty: "No skills shared yet.",
  publishHeading: "Share a skill",
  nameLabel: "Name",
  descriptionLabel: "Short description (optional)",
  bodyLabel: "Skill text",
  publish: "Publish",
  saveDraft: "Save draft",
  publishDraft: "Publish draft",
  publishing: "Saving…",
  revoke: "Revoke",
  discardDraft: "Discard draft",
  revoking: "Revoking…",
  discarding: "Discarding…",
  draftBadge: "Draft",
  versionLabel: (version: number) => `v${version}`,
  bytesLabel: (bytes: number, max: number) =>
    `${Math.ceil(bytes / 1024)} / ${Math.round(max / 1024)} KB`,
  tooLarge: "Skill text is over 64KB.",
  published: "Skill published.",
  draftSaved: "Draft saved.",
  revoked: "Skill revoked.",
  /** Product Shared visibility — exact EN (same as Library disabled.*). */
  disabledAdd: "Only the project owner can add items.",
  disabledEdit: "Only the project owner can edit this.",
  disabledPublish: "Only the project owner can publish.",
  disabledDelete: "Only the project owner can delete this.",
} as const;
