export {
  AGENT_WITCH_LIVE_APP_HOST as AGENT_WITCH_LOCAL_APP_HOST,
  AGENT_WITCH_LIVE_APP_LOOPBACK_ORIGIN as AGENT_WITCH_LOCAL_APP_LOOPBACK_ORIGIN,
  AGENT_WITCH_LIVE_APP_ORIGIN as AGENT_WITCH_LOCAL_APP_ORIGIN,
  AGENT_WITCH_LIVE_APP_PORT as AGENT_WITCH_LOCAL_APP_PORT,
} from "@agent-witch/shared/network";
