/** Companies & rules hub: validation, status and layout strings. */
export const COMPANIES_RULES_HUB_UI_COPY = {
  policySaveFailBody: "Nothing changed. Check your connection and try again.",
  policyLoading: "Loading policy…",
  unsavedChange: "Unsaved change",
  pickDifferentPolicy: "Pick a different policy first.",
  settingsBack: "Back to Companies & rules",
  crumbManage: "Manage",
  crumbHub: "Companies & rules",
  settingsTitle: "Company settings",
  createNoCompany:
    "Create a company to set who can send tasks to this computer.",
  nameEnter: "Enter a company name.",
  nameShort: "Use at least 2 characters.",
  nameDuplicate: "You already have a company with this name.",
  newCompanyTitle: "New company",
  cancel: "Cancel",
  youRole: "You:",
  peopleCount: "people",
  companyPickerAria: "Company",
  inviteEmailLabel: "Email",
  inviteRoleLabel: "Role",
  inviteEnter: "Enter an email address.",
  inviteInvalid: "Enter a valid email, like name@company.com.",
  inviteDuplicate: "This person is already in the company.",
  onlyAdminsInvite: "Only company admins can invite people.",
  youChip: "You",
  colPerson: "Person",
  colRole: "Role",
  colLastActive: "Last active",
  onlineNow: "Online now",
  removeMemberText:
    "{name} loses access to {company}, its projects and its computers right away. You can invite them again later.",
  runsNewTask: "New task",
  runsStatusWaiting: "Waiting for approval",
  runsStatusRunning: "Running",
  runsStatusDone: "Done",
  runsStatusDeclined: "Declined",
  runsStatusFailed: "Failed",
  runsStatusExpired: "Expired",
  runsViewReport: "View report",
  deleteOwnerOnly: "Only the company owner can delete it.",
  deleteAlsoMembers: "Also delete all users in this company",
  policyOnFor: "is now on for",
} as const;
