import { AGENT_WITCH_PRODUCT_NAME } from "@/lib/agentWitch/agentWitchProductName.constant";

export const MARKETING_PRIVACY_COPY = {
  title: "Privacy Policy",
  lastUpdated: "September 16, 2026",
  intro: `${AGENT_WITCH_PRODUCT_NAME} (“we”, “us”) operates the Agent Witch web application and related services at agentwitch.com. This policy describes how we handle information when you use our product.`,
  sections: [
    {
      heading: "Information we collect",
      body: "We collect account information you provide (such as name and email), usage data needed to run tasks and show job history, and technical logs required to operate and secure the service.",
    },
    {
      heading: "How we use information",
      body: "We use this information to authenticate you, run and record agent tasks on your team’s Macs, provide support, and improve reliability and security. We do not sell personal information.",
    },
    {
      heading: "Retention and security",
      body: "We retain data as long as your account is active or as needed for legal and operational purposes. We apply industry-standard safeguards; no method of transmission over the Internet is 100% secure.",
    },
    {
      heading: "Your choices",
      body: "You may request access, correction, or deletion of your account data by contacting us. Some data may be retained where required by law or for legitimate business records.",
    },
    {
      heading: "Updates",
      body: "We may update this policy from time to time. Material changes will be posted on this page with an updated date.",
    },
    {
      heading: "Contact",
      body: "Questions about privacy: contact your organization’s Agent Witch administrator or reach us through the support channel provided in your account.",
    },
  ],
} as const;

export const MARKETING_TERMS_COPY = {
  title: "Terms of Service",
  lastUpdated: "September 16, 2026",
  intro: `These Terms govern your use of ${AGENT_WITCH_PRODUCT_NAME} and the agentwitch.com service. By creating an account or using the product, you agree to these Terms.`,
  sections: [
    {
      heading: "Service",
      body: "Agent Witch provides a control plane to dispatch AI agent tasks to Mac workers your team configures, including optional approval workflows and job history.",
    },
    {
      heading: "Accounts and acceptable use",
      body: "You are responsible for your account credentials and for tasks you dispatch. You agree not to misuse the service, attempt unauthorized access, or use it in violation of applicable law or your organization’s policies.",
    },
    {
      heading: "Team and Mac workers",
      body: "Tasks may run on Macs you or your organization connect. You are responsible for software installed on those machines and for data processed locally by agent tools.",
    },
    {
      heading: "Availability",
      body: "We strive for reliable service but do not guarantee uninterrupted availability. Features may change as we improve the product.",
    },
    {
      heading: "Disclaimer",
      body: "The service is provided “as is” to the extent permitted by law. Agent outputs are generated by third-party AI tools on your infrastructure; review results before relying on them for critical decisions.",
    },
    {
      heading: "Contact",
      body: "For terms questions, contact your organization’s administrator or the support channel listed in your account.",
    },
  ],
} as const;
