export const BILLING_COPY = {
  planHeading: "Your plan",
  loading: "Loading your plan…",
  loadError: "Could not load your plan. Try again.",
  tryAgain: "Try again",
  cancelAnytime: "Cancel anytime.",
  cloudStorageOn: "Cloud message storage is on.",
  cloudStorageOff: "Cloud message storage is off until you start paid billing.",
  adminFreeEdge:
    "You are on permanent Free set by an admin. This is not a self-serve plan.",
  trialGateClosed:
    "New trials are paused right now. Choose Pro or Team to continue.",
  trialEndsPrefix: "Trial ends",
  seatsLabel: "Seats",
  computersLabel: "Computers",
  assistantsLabel: "Assistants you can connect",
  upgradeStubPending: "Checkout is not live yet. Your plan options stay here.",
  portalStubPending: "Billing portal is not live yet.",
  computerLimit:
    "You are at your computer limit: {linked} of {max} computers are linked{split}. Offline computers still count. Remove one you no longer use, or upgrade to free a slot.",
  assistantLimit:
    "You are at your assistant connect limit ({max}). Disconnect an assistant or upgrade. Server still enforces the limit.",
  adminCostHeading: "Trial and Free cost control",
  adminCostLoading: "Loading cost control…",
  adminCostError: "Could not load cost control.",
  adminBudgetLabel: "Budget",
  adminSpendLabel: "Trial + admin Free spend",
  adminStatusLabel: "Status",
  adminGateLabel: "Trial gate",
  adminSignalsHeading: "Signal breakdown",
  adminSetFreeOn: "Grant permanent Free",
  adminSetFreeOff: "Remove permanent Free",
  adminSetFreeDone: "Permanent Free updated.",
  adminSetFreeError: "Could not update permanent Free.",
  adminSetPlanApply: "Set plan",
  adminSetPlanDone: "Plan updated.",
  adminSetPlanError: "Could not update plan.",
} as const;
