import { PROJECT_MEMBERSHIP_POLL_SILENCE_STATUS } from "@/lib/projects/acl/membershipDeliveryMode.constant";

/** Activity messenger copy — matches design spec.md strings. */
export const AWC_PROJECT_MESSENGER_COPY = {
  tab: "Activity",
  listHeading: "Threads",
  wholeName: "Whole project",
  wholeSub: "Message every bot",
  kindBot: "Bot",
  statusWorking: "Working",
  statusIdle: "Idle",
  statusSilent: "Silent",
  statusChecksOnDemand: PROJECT_MEMBERSHIP_POLL_SILENCE_STATUS,
  stateReceived: "Received",
  stateGotIt: "Got it",
  stateWorking: "Working on it",
  stateDone: "Done",
  stateBlocked: "Blocked",
  stateWaiting: "Waiting for {name} to confirm",
  stateNoAnswer: "No answer — blocked",
  stateChecksOnDemand: PROJECT_MEMBERSHIP_POLL_SILENCE_STATUS,
  composerLabel: "Message",
  composerPlaceholder: "Write a message…",
  composerNeedsReply: "Needs a reply",
  composerSend: "Send",
  composerHint: "Sends a project message and wakes the bot",
  modeMessage: "Message",
  modeTask: "Task",
  modeMessageHint: "Project chat — bots see it in this thread.",
  modeTaskHint: "Assign a short task to one bot (from Owner).",
  taskAssigneeLabel: "Assign to",
  taskAssigneePlaceholder: "Select…",
  taskKindLabel: "Type (optional)",
  taskKindPlaceholder: "task.assign",
  taskSummaryLabel: "What needs doing",
  taskSummaryPlaceholder: "Describe what needs doing…",
  taskSummaryCounter: "{n} / 200",
  taskRefsToggle: "Attach references",
  taskSend: "Send task",
  taskAssigneeRequired: "Pick who gets this task.",
  taskSummaryRequired: "Say what needs doing.",
  taskSendFailed: "Could not assign that task. Try again.",
  taskSent: "Task sent to {name}.",
  messageSent: "Sent to {name}.",
  viewerBanner:
    "You can read this project. Only the owner and members can send messages.",
  emptyTitle: "No bots yet",
  emptyBody: "Invite a bot on Bots & people, then come back to message it.",
  emptyCta: "Open Bots & people",
  a11yBack: "Back to threads",
  loading: "Loading threads…",
  loadingThread: "Loading messages…",
  unavailable:
    "Messenger is not available on this deploy yet. Stay on this page — it will open when ready.",
  sendFailed: "Could not send that message. Try again.",
  pinned: "Pinned",
  /** (i) no owner computer — browser keeps the long-term chat copy. EN: Product may refine. */
  noComputerHintLabel: "About chat history",
  noComputerHint:
    "This project has no computer yet, so this browser keeps the chat history. Adding a computer is safer.",
} as const;
