import { PROJECT_MEMBERSHIP_POLL_SILENCE_STATUS } from "@/lib/projects/acl/membershipDeliveryMode.constant";

/** Project messenger copy — tab label Chat (Soft DROP Activity label). */
export const AWC_PROJECT_MESSENGER_COPY = {
  tab: "Chat",
  listHeading: "Threads",
  wholeName: "Whole project",
  wholeSub: "Message every assistant",
  kindBot: "Assistant",
  statusWorking: "Working",
  statusIdle: "Idle",
  statusSilent: "Silent",
  statusChecksOnDemand: PROJECT_MEMBERSHIP_POLL_SILENCE_STATUS,
  stateReceived: "Received",
  stateGotIt: "Got it",
  stateWorking: "Working on it",
  stateDone: "Done",
  stateBlocked: "Blocked",
  stateWaiting: "Waiting for {name} to confirm",
  stateNoAnswer: "No answer — blocked",
  stateChecksOnDemand: PROJECT_MEMBERSHIP_POLL_SILENCE_STATUS,
  composerLabel: "Message",
  composerPlaceholder: "Write a message…",
  composerNeedsReply: "Needs a reply",
  composerSend: "Send",
  composerHint: "Sends a project message and wakes the assistant",
  modeMessage: "Message",
  modeTask: "Task",
  modeMessageHint: "Project chat — assistants see it in this thread.",
  modeTaskHint: "Assign a short task to one assistant (from Owner).",
  taskAssigneeLabel: "Assign to",
  taskAssigneePlaceholder: "Select…",
  taskKindLabel: "Type (optional)",
  taskKindPlaceholder: "task.assign",
  taskSummaryLabel: "What needs doing",
  taskSummaryPlaceholder: "Describe what needs doing…",
  taskSummaryCounter: "{n} / 200",
  taskRefsToggle: "Attach references",
  taskSend: "Send task",
  taskAssigneeRequired: "Pick who gets this task.",
  taskSummaryRequired: "Say what needs doing.",
  taskSendFailed: "Could not assign that task. Try again.",
  taskSent: "Task sent to {name}.",
  messageSent: "Sent to {name}.",
  viewerBanner:
    "You can read this project. Only the owner and members can send messages.",
  emptyTitle: "No messages yet",
  emptyBody: "Say hello or @ an assistant to assign work.",
  emptyCta: "Open Bots & people",
  a11yBack: "Back to threads",
  loading: "Loading threads…",
  loadingThread: "Loading messages…",
  unavailable:
    "Messenger is not available on this deploy yet. Stay on this page — it will open when ready.",
  sendFailed: "Could not send that message. Try again.",
  pinned: "Pinned",
  /** (i) no owner computer — browser keeps the chat copy for now. EN: Product NEEDLE. */
  noComputerHintLabel: "Where chat history is kept",
  noComputerHint:
    "This browser keeps this project's chat history for now. Add a computer to keep a lasting copy.",
  loadOlder: "Load older",
  loadingOlder: "Loading older messages…",
  startOfConversation: "Start of conversation",
  projectComputerOffline:
    "Lost connection to the project computer. Older messages will load when it's back online.",
  projectComputerOfflineRetry: "Retry",
} as const;
