/** Activity messenger copy — matches design spec.md strings. */
export const AWC_PROJECT_MESSENGER_COPY = {
  tab: "Activity",
  listHeading: "Threads",
  wholeName: "Whole project",
  wholeSub: "Message every bot",
  kindBot: "Bot",
  statusWorking: "Working",
  statusIdle: "Idle",
  statusSilent: "Silent",
  stateReceived: "Received",
  stateGotIt: "Got it",
  stateWorking: "Working on it",
  stateDone: "Done",
  stateBlocked: "Blocked",
  stateWaiting: "Waiting for {name} to confirm",
  stateNoAnswer: "No answer — blocked",
  composerLabel: "Message",
  composerPlaceholder: "Write a message…",
  composerNeedsReply: "Needs a reply",
  composerSend: "Send",
  composerHint: "Sends a project message and wakes the bot",
  viewerBanner:
    "You can read this project. Only the owner and members can send messages.",
  emptyTitle: "No bots yet",
  emptyBody: "Invite a bot on Bots & people, then come back to message it.",
  emptyCta: "Open Bots & people",
  a11yBack: "Back to threads",
  loading: "Loading threads…",
  loadingThread: "Loading messages…",
  unavailable:
    "Messenger is not available on this deploy yet. Stay on this page — it will open when ready.",
  sendFailed: "Could not send that message. Try again.",
  pinned: "Pinned",
} as const;
