/** Header-bell inbox EN — Notifications EN-PASS + CLAUDE-BRIEF (2026-10-07). */
export const NOTIFICATIONS_FILTERS = [
  { id: "all", label: "All" },
  { id: "unread", label: "Unread" },
  { id: "approvals", label: "Approvals" },
] as const;

export type NotificationsFilterId =
  (typeof NOTIFICATIONS_FILTERS)[number]["id"];

export const NOTIFICATIONS_COPY = {
  breadcrumbRoot: "Inbox",
  h1: "Notifications",
  tip: "Updates from your projects and anything that needs your OK. What reaches you by email is set on your Account page.",
  accessOrientation:
    "Join requests also stay in each project's Access panel. Approving in either place does the same thing.",
  safetyOrientation:
    "Why a task asks first is set by the safety rules inside each project.",
  markAllRead: "Mark all read",
  settingsLink: "Notification settings",
  settingsSr: "on your Account page",
  settingsHref: "/account?tab=notify",
  seeAll: "See all notifications",
  seeAllHref: "/notifications",
  loading: "Loading notifications…",
  tryAgain: "Try again",
  loadError: "Could not load notifications",
  showOlder: "Show older",
  olderDone: "That is everything from the last 30 days.",
  olderError: "Could not load older notifications",
  approve: "Approve",
  deny: "Deny",
  approving: "Approving…",
  denying: "Denying…",
  cancel: "Cancel",
  waitingForYou: "Waiting for you",
  waitingMins: "Waiting for you · {mins} min left",
  approved: "Approved",
  denied: "Denied",
  timedOut: "Timed out",
  approvedRun: "Approved by you {when}. It is running on {computer}.",
  approvedJoin: "Approved by you {when}. {who} can now open {project}.",
  deniedRun: "Denied by you {when}. Nothing ran.",
  deniedJoin: "Denied by you {when}. {who} can ask again later.",
  timedOutLine:
    "Nobody answered within {mins} min, so it stopped at {clock}. Nothing ran.",
  doneWhenFallback: "earlier",
  alsoOn: "Also on {link}",
  alsoIn: "Also in {link}",
  accessSuffix: " › Access",
  computersHref: "/device",
  projectsHref: "/projects",
  checksOnDemand: "Checks in only when asked",
  thisComputer: "This computer",
  denyJoinTitle: "Deny {who}?",
  denyJoinBody:
    "{who} will not get access to {project}. They can ask again later.",
  denyRunTitle: "Deny this task?",
  denyRunBody: "{who} will not run “{task}” on {computer}.",
  markRead: "Mark as read",
  markReadAria: "Mark as read: {title}",
  approveAria: "Approve: {title}",
  denyAria: "Deny: {title}",
  filterGroupLabel: "Filter notifications",
  filterGroupLabelPopover: "Filter notifications in this panel",
  loadErrorHint: "Check your connection, then try again. Nothing was lost.",
  loadingOlder: "Loading older notifications…",
  subtitleUnread: "{n} unread",
  subtitleNone: "Nothing unread",
  subtitleWaiting: "{m} waiting for your approval",
  calloutOne: "1 item is waiting for your approval",
  calloutMany: "{m} items are waiting for your approval",
  showApprovals: "Show approvals",
  fewerEmailsPre: "Want fewer emails? Change what reaches you in ",
  bellLabel: "Notifications, {n} unread, {m} waiting for approval",
  opensNewTab: "(opens in a new tab)",
  unreadSr: "Unread.",
  signedOut: {
    title: "Sign in to see your notifications",
    body: "Updates from your projects and anything waiting for your approval show up here.",
    signIn: "Sign in",
    download: "Download AgentWitch Local",
  },
  empty: {
    all: {
      title: "No notifications yet",
      body: "When an assistant finishes work or someone asks to join, it shows up here.",
    },
    unread: {
      title: "You are all caught up",
      body: "Nothing new since you last looked.",
    },
    approvals: {
      title: "Nothing is waiting for you",
      body: "Join requests and tasks that need your OK show up here.",
    },
  },
  popoverTitle: "Notifications",
} as const;
