import type { NotificationItem } from "@/features/notifications/notificationsDemoItems.constant";

export const NOTIFICATIONS_DEMO_REST: readonly NotificationItem[] = [
  {
    id: "r2",
    kind: "run",
    who: "Cursor",
    task: "Nightly cleanup of old builds",
    project: "release-train",
    computer: "linux",
    computerLabel: "Linux device",
    atLabel: "9 hr ago",
    unread: false,
    state: "timeout",
    rule: "Ask me before deleting files",
    expiredAtLabel: "02:30",
    waitMins: 30,
  },
  {
    id: "n3",
    kind: "limit",
    title: "All 3 assistant spots on Pro are in use",
    text: "To connect another assistant, remove one or move to Team.",
    atLabel: "20 hr ago",
    unread: true,
    href: "/pricing",
    linkLabel: "See plans",
  },
  {
    id: "j3",
    kind: "join",
    who: "Jonas Weber",
    whoKind: "person",
    email: "jonas@infusionlabs.io",
    role: "Member",
    project: "infusion",
    atLabel: "26 hr ago",
    unread: false,
    state: "approved",
    doneAtLabel: "25 hr ago",
  },
  {
    id: "n4",
    kind: "invite",
    title: "Jonas Weber accepted your invite",
    text: "He can now open infusion as a member.",
    project: "infusion",
    atLabel: "25 hr ago",
    unread: false,
    href: "/projects",
    linkLabel: "Open project",
  },
  {
    id: "n5",
    kind: "bill",
    title: "Your trial ends in 5 days",
    text: "Pick Pro or Team to keep your projects running. Billing emails are always on.",
    atLabel: "2 days ago",
    unread: false,
    href: "/pricing",
    linkLabel: "Choose a plan",
  },
  {
    id: "n6",
    kind: "fail",
    title: "Weekly report did not run",
    text: "Linux device was offline at 06:00. It runs again next Monday.",
    project: "release-train",
    atLabel: "3 days ago",
    unread: false,
    href: "/automations",
    linkLabel: "Open Automations",
  },
  {
    id: "n9",
    kind: "bill",
    title: "Invoice INV-1043 is ready",
    text: "$87.00 for the last month.",
    atLabel: "3 days ago",
    unread: false,
    href: "/pricing",
    linkLabel: "View invoice",
  },
  {
    id: "n7",
    kind: "computer",
    title: "Grey - Study needs an update",
    text: "Open AgentWitch Local on that computer to update it.",
    atLabel: "4 days ago",
    unread: false,
    href: "/device",
    linkLabel: "Open computers",
  },
];
