import type { NotificationItem } from "@/features/notifications/notificationsDemoItems.constant";

export const NOTIFICATIONS_DEMO_FIRST: readonly NotificationItem[] = [
  {
    id: "r1",
    kind: "run",
    who: "Codex",
    task: "Update packages and run the checks",
    project: "agentwitch",
    computer: "here",
    computerLabel: "This computer",
    atLabel: "6 min ago",
    unread: true,
    state: "pending",
    minsLeft: 24,
    rule: "Ask me before changing packages",
    files: ["package.json", "package-lock.json", "scripts/check.sh"],
  },
  {
    id: "j1",
    kind: "join",
    who: "Maya Chen",
    whoKind: "person",
    email: "maya@northwind.dev",
    role: "Member",
    project: "infusion",
    atLabel: "12 min ago",
    unread: true,
    state: "pending",
    note: "I would like to help review the release notes this week.",
  },
  {
    id: "j2",
    kind: "join",
    who: "Release helper",
    whoKind: "assistant",
    runs: "Claude Code",
    role: "Assistant",
    project: "release-train",
    atLabel: "38 min ago",
    unread: true,
    state: "pending",
    delivery: "demand",
  },
  {
    id: "j4",
    kind: "join",
    who: "Sam Ortiz",
    whoKind: "person",
    email: "sam@northwind.dev",
    role: "Viewer",
    project: "northwind-docs",
    owner: "Maya Chen",
    atLabel: "70 min ago",
    unread: false,
    state: "pending",
    note: "I would like to read the docs rules and reports.",
  },
  {
    id: "n8",
    kind: "billpay",
    title: "Payment failed",
    text: "The card ending 4242 was declined. Update it to keep your plan active.",
    atLabel: "5 min ago",
    unread: true,
    href: "/pricing",
    linkLabel: "Update payment",
  },
  {
    id: "n1",
    kind: "auto",
    title: "Morning summary finished",
    text: "The summary for 07 Oct is ready in the project.",
    project: "agentwitch",
    atLabel: "95 min ago",
    unread: true,
    href: "/automations",
    linkLabel: "Open Automations",
  },
  {
    id: "n2",
    kind: "done",
    title: "Claude Code finished “Fix sign-in copy”",
    text: "3 files changed. Ready for your review.",
    project: "infusion",
    atLabel: "2 hr ago",
    unread: false,
    href: "/projects",
    linkLabel: "Open project",
  },
];
