export const AWC_PROJECT_PITFALLS_COPY = {
  title: "Pitfalls",
  hint: (deviceDisplayName: string) =>
    `Known traps in this project and how to avoid them. Edit them on ${deviceDisplayName}.`,
  panelHint: (active: number, max: number, deviceDisplayName: string) =>
    `Known traps in this project and how to avoid them. ${active} of ${max} active. Turn them on, off, or edit them on ${deviceDisplayName}.`,
  manageOnMac: "Manage on Mac",
  loading: "Loading…",
  empty: "No pitfalls for this project.",
  unavailable: "Pitfalls are unavailable for this project right now.",
  noMatch: "No pitfalls match.",
  filterGroupLabel: "Filter by severity",
  filterAll: "All",
  searchLabel: "Search pitfalls",
  searchPlaceholder: "Search by keyword, e.g. push, build",
  fixLabel: "Fix",
  avoidLabel: "How to avoid:",
  triggersLabel: "Triggers",
  triggersOnLabel: "Triggers on:",
  neverHit: "Never hit",
  lastHit: (relative: string) => `Last hit ${relative}`,
  notUpdatedYet: "Not updated yet",
  updated: (date: string) => `Updated ${date}`,
  activeCount: (active: number, max: number) => `${active} of ${max} active`,
  severity: {
    block: "Must fix",
    warn: "Warning",
    info: "Note",
  },
  source: {
    seed: "Built-in",
    project: "This project",
    retired: "Retired",
  },
} as const;
