export {
  AGENT_WITCH_AUTOMATION_SCHEDULER_LAUNCH_AGENT_LABEL,
  AGENT_WITCH_UPDATER_INTERVAL_SEC,
  AGENT_WITCH_UPDATER_LAUNCH_AGENT_LABEL,
  AGENT_WITCH_WAKE_LAUNCH_AGENT_LABEL,
  AGENT_WITCH_WATCHDOG_LAUNCH_AGENT_LABEL,
} from "@agent-witch/install-macos-launch";
