import fs from "node:fs";
import path from "node:path";

import { AWC_STORYBOOK_PAGE_MANIFEST } from "../src/utils/storybook/awc/awcStorybookPageManifest.constant";
import { AWL_STORYBOOK_PAGE_MANIFEST } from "../src/utils/storybook/awl/awlStorybookPageManifest.constant";

const toExportName = (pageId: string, status: string): string =>
  `${pageId.replaceAll("-", "_")}_${status}`;

const writeAwcStories = (): void => {
  const exports = AWC_STORYBOOK_PAGE_MANIFEST.flatMap((entry) =>
    entry.statuses.map((status) => {
      const exportName = toExportName(entry.id, status);
      return `export const ${exportName} = awcPageStories.${exportName};`;
    }),
  );

  const contents = `/* eslint-disable -- generated by scripts/generateStorybookPageStories.ts */
import { awcPageStories } from "@/utils/storybook/stories/awcPageStories.shared";

export default {
  title: "AWC/Pages",
  parameters: { layout: "fullscreen" },
};

${exports.join("\n")}
`;

  fs.writeFileSync(
    path.join(
      process.cwd(),
      "src/utils/storybook/stories/AWC.pages.stories.tsx",
    ),
    contents,
    "utf8",
  );
};

const AWL_PROMPT_OPTIMIZER_PAGE_IDS = new Set([
  "prompt-optimizer",
  "prompt-optimizer-guide",
]);

const AWL_HOME_TASK_PAGE_IDS = new Set(["home", "task"]);
const AWL_STATUS_WRITER_PAGE_IDS = new Set([
  "status",
  "writer-api",
  "writer-sessions",
]);
const AWL_PROJECTS_HARNESS_PAGE_IDS = new Set([
  "projects",
  "project",
  "harness",
]);
const AWL_DIAGNOSTICS_PAGE_IDS = new Set([
  "knowledge",
  "history",
  "errors",
  "traffic",
]);

const writeAwlGroupStories = (input: {
  readonly fileName: string;
  readonly title: string;
  readonly importPath: string;
  readonly storiesBinding: string;
  readonly pageIds: ReadonlySet<string>;
}): void => {
  const pages = AWL_STORYBOOK_PAGE_MANIFEST.filter((entry) =>
    input.pageIds.has(entry.id),
  );
  const exports = pages.flatMap((entry) =>
    entry.statuses.map((status) => {
      const exportName = toExportName(entry.id, status);
      return `export const ${exportName} = ${input.storiesBinding}.${exportName};`;
    }),
  );

  const contents = `/* eslint-disable -- generated by scripts/generateStorybookPageStories.ts */
import { ${input.storiesBinding} } from "${input.importPath}";

export default {
  title: "${input.title}",
  parameters: { layout: "fullscreen" },
};

${exports.join("\n")}
`;

  fs.writeFileSync(
    path.join(process.cwd(), "src/utils/storybook/stories", input.fileName),
    contents,
    "utf8",
  );
};

const writeAwlStories = (): void => {
  writeAwlGroupStories({
    fileName: "AWL.home-task.pages.stories.tsx",
    title: "AWL/Pages/Home & task",
    importPath: "@/utils/storybook/stories/awlHomeTaskPageStories.shared",
    storiesBinding: "awlHomeTaskPageStories",
    pageIds: AWL_HOME_TASK_PAGE_IDS,
  });

  writeAwlGroupStories({
    fileName: "AWL.status-writer.pages.stories.tsx",
    title: "AWL/Pages/Status & writer",
    importPath: "@/utils/storybook/stories/awlStatusWriterPageStories.shared",
    storiesBinding: "awlStatusWriterPageStories",
    pageIds: AWL_STATUS_WRITER_PAGE_IDS,
  });

  writeAwlGroupStories({
    fileName: "AWL.projects-harness.pages.stories.tsx",
    title: "AWL/Pages/Projects & harness",
    importPath:
      "@/utils/storybook/stories/awlProjectsHarnessPageStories.shared",
    storiesBinding: "awlProjectsHarnessPageStories",
    pageIds: AWL_PROJECTS_HARNESS_PAGE_IDS,
  });

  writeAwlGroupStories({
    fileName: "AWL.diagnostics.pages.stories.tsx",
    title: "AWL/Pages/Diagnostics",
    importPath: "@/utils/storybook/stories/awlDiagnosticsPageStories.shared",
    storiesBinding: "awlDiagnosticsPageStories",
    pageIds: AWL_DIAGNOSTICS_PAGE_IDS,
  });

  const promptOptimizerPages = AWL_STORYBOOK_PAGE_MANIFEST.filter((entry) =>
    AWL_PROMPT_OPTIMIZER_PAGE_IDS.has(entry.id),
  );
  const poExports = promptOptimizerPages.flatMap((entry) =>
    entry.statuses.map((status) => {
      const exportName = toExportName(entry.id, status);
      return `export const ${exportName} = awlPromptOptimizerPageStories.${exportName};`;
    }),
  );

  const poContents = `/* eslint-disable -- generated by scripts/generateStorybookPageStories.ts */
import { awlPromptOptimizerPageStories } from "@/utils/storybook/stories/awlPromptOptimizerPageStories.shared";

export default {
  title: "AWL/Prompt optimizer",
  parameters: { layout: "fullscreen" },
};

${poExports.join("\n")}
`;

  fs.writeFileSync(
    path.join(
      process.cwd(),
      "src/utils/storybook/stories/AWL.prompt-optimizer.pages.stories.tsx",
    ),
    poContents,
    "utf8",
  );

  const legacyPagesPath = path.join(
    process.cwd(),
    "src/utils/storybook/stories/AWL.pages.stories.tsx",
  );
  if (fs.existsSync(legacyPagesPath)) {
    fs.unlinkSync(legacyPagesPath);
  }
};

writeAwcStories();
writeAwlStories();

console.log(
  `Generated AWC (${AWC_STORYBOOK_PAGE_MANIFEST.length} pages) and AWL (${AWL_STORYBOOK_PAGE_MANIFEST.length} pages) Storybook CSF exports.`,
);
