import fs from "node:fs";
import path from "node:path";

import { AWC_STORYBOOK_PAGE_MANIFEST } from "../src/utils/storybook/awc/awcStorybookPageManifest.constant";
import { AWL_STORYBOOK_PAGE_MANIFEST } from "../src/utils/storybook/awl/awlStorybookPageManifest.constant";

const toExportName = (pageId: string, status: string): string =>
  `${pageId.replaceAll("-", "_")}_${status}`;

const writeAwcStories = (): void => {
  const exports = AWC_STORYBOOK_PAGE_MANIFEST.flatMap((entry) =>
    entry.statuses.map((status) => {
      const exportName = toExportName(entry.id, status);
      return `export const ${exportName} = awcPageStories.${exportName};`;
    }),
  );

  const contents = `/* eslint-disable -- generated by scripts/generateStorybookPageStories.ts */
import { awcPageStories } from "@/utils/storybook/stories/awcPageStories.shared";

export default {
  title: "AWC/Pages",
  parameters: { layout: "fullscreen" },
};

${exports.join("\n")}
`;

  fs.writeFileSync(
    path.join(
      process.cwd(),
      "src/utils/storybook/stories/AWC.pages.stories.tsx",
    ),
    contents,
    "utf8",
  );
};

const writeAwlStories = (): void => {
  const exports = AWL_STORYBOOK_PAGE_MANIFEST.flatMap((entry) =>
    entry.statuses.map((status) => {
      const exportName = toExportName(entry.id, status);
      return `export const ${exportName} = awlPageStories.${exportName};`;
    }),
  );

  const contents = `/* eslint-disable -- generated by scripts/generateStorybookPageStories.ts */
import { awlPageStories } from "@/utils/storybook/stories/awlPageStories.shared";

export default {
  title: "AWL/Pages",
  parameters: { layout: "fullscreen" },
};

${exports.join("\n")}
`;

  fs.writeFileSync(
    path.join(
      process.cwd(),
      "src/utils/storybook/stories/AWL.pages.stories.tsx",
    ),
    contents,
    "utf8",
  );
};

writeAwcStories();
writeAwlStories();

console.log(
  `Generated AWC (${AWC_STORYBOOK_PAGE_MANIFEST.length} pages) and AWL (${AWL_STORYBOOK_PAGE_MANIFEST.length} pages) Storybook CSF exports.`,
);
