export type { AgentWitchLocalLayout } from "@agent-witch/install-layout/types";

export {
  AGENT_WITCH_ACTIVE_PROFILE_FILE_NAME,
  AGENT_WITCH_DEVICE_KEYPAIR_FILE_NAME,
  AGENT_WITCH_ERROR_LOG_FILE_NAME,
  AGENT_WITCH_HARNESS_DIR_NAME,
  AGENT_WITCH_HARNESS_SETS_DIR_NAME,
  AGENT_WITCH_INSTALL_DIR_NAME,
  AGENT_WITCH_LOCAL_INSTALL_DIR_NAME,
  AGENT_WITCH_LOCAL_LAUNCH_AGENT_PREFIX,
  AGENT_WITCH_LOCAL_WAKE_PORT,
  AGENT_WITCH_LOGS_DIR_NAME,
  AGENT_WITCH_MAIN_LOG_FILE_NAME,
  AGENT_WITCH_MANIFEST_FILE_NAME,
  AGENT_WITCH_PROD_INSTALL_DIR_NAME,
  AGENT_WITCH_PROD_LAUNCH_AGENT_PREFIX,
  AGENT_WITCH_PROD_WAKE_PORT,
  AGENT_WITCH_PROFILES_DIR_NAME,
  AGENT_WITCH_PROJECTS_DIR_NAME,
  AGENT_WITCH_REPORTS_DIR_NAME,
} from "@agent-witch/install-layout/types";

export {
  isAgentWitchLocalInstallDir,
  readActiveProfileEmailFromFile,
  resolveActiveProfileEmail,
  resolveActiveProfileEmailFromEnv,
  resolveAgentWitchAppBundlePath,
  resolveAgentWitchAppDir,
  resolveAgentWitchDefaultWakePort,
  resolveAgentWitchDeviceKeypairPath,
  resolveAgentWitchErrorLogPath,
  resolveAgentWitchInstallDir,
  resolveAgentWitchLaunchAgentPrefix,
  resolveAgentWitchLocalLayout,
  resolveAgentWitchLogsDir,
  resolveAgentWitchMainLogPath,
  resolveAgentWitchProjectsDir,
  resolveAgentWitchReportsDir,
  sanitizeProfileEmailForDir,
  sanitizeProfileEmailForLaunchAgentLabel,
} from "@agent-witch/install-layout";
