/** Project Settings → Connections → Linear task sync (plain English). */
export const PROJECT_TASK_SYNC_COPY = {
  heading: "Task sync",
  loading: "Loading task sync…",
  loadError: "Could not load task sync.",
  retry: "Retry",
  switchLabel: "Sync project tasks with Linear",
  teamLabel: "Linear team",
  teamPlaceholder: "Choose a team",
  teamHint: "Choose a team to turn sync on.",
  importNewLabel: "Also create AgentWitch tasks from new Linear issues",
  linkedTasks: "Linked tasks: {count}",
  lastSynced: "Last synced: {time}",
  neverSynced: "Last synced: never",
  webhookOn: "Linear → AgentWitch updates: on (webhook)",
  webhookOff: "Linear → AgentWitch updates: off (webhook)",
  syncNow: "Sync now",
  syncing: "Syncing… ({count} left)",
  syncSummary: "Pushed {pushed}, failed {failed}",
  teamRequired: "Choose a team first.",
  notConnected: "Linear is not connected.",
  syncDisabled: "Turn sync on before syncing.",
  saveError: "Could not save. Try again.",
  syncError: "Sync failed. Try again.",
} as const;
