/** EN PASS Tasks tab copy — prefer "assistant"; exact offline EN. */
export const PROJECT_PAGE_TASKS_COPY = {
  tab: "Tasks",
  intro: "Tasks assigned in this project.",
  aria: "Project tasks",
  empty: "No tasks yet",
  emptyFiltered: "No matching tasks",
  emptyAssign: "Assign task",
  clearFilters: "Clear filters",
  filterAllAssistants: "All assistants",
  filterAllStatus: "All status",
  statusQueued: "Queued",
  statusRunning: "Running",
  statusDone: "Done",
  statusFailed: "Failed",
  statusCancelled: "Cancelled",
  /** Exact design EN — no trailing period. */
  offline: "Connection to the project computer was lost",
  offlineRetry: "Retry",
  planCounts: (used: number, max: number) =>
    `${used} of ${max} tasks this plan`,
  planTip: "Plan limit for task records. Resets monthly.",
  taskInfo: "Task info",
  taskInfoTip: "Cloud keeps title, status and times only.",
  /** Design HTML heading (brief said Status timeline — tight equivalent). */
  statusTimeline: "Status",
  openHistory: "Open history",
  /** Stays in Chat (product rule) — not rendered on Tasks detail. */
  loadOlder: "Load older",
  openReport: "Open report",
  openTask: "Open task",
  openInTasks: "Open in Tasks",
  backToList: "← Tasks",
  assignTitle: "Assign task",
  assignAssistant: "Assistant",
  assignPrompt: "Task",
  assignSubmit: "Assign",
  assignPending: "Assigning…",
  assignCancel: "Cancel",
  assignPeersLoading: "Loading assistants…",
  assignPeersEmpty: "No assistants ready to assign yet",
  assignPeersLoadFailed: "Could not load assistants. Try again.",
  assignSummaryCounter: (n: number) => `${n} / 200`,
  assignGitMetaHint:
    "Branch and worktree stay on this computer for now. The assign request sends the task text.",
  branch: "Branch",
  worktree: "Worktree",
  createWorktree: "Create worktree",
  worktreeName: "Worktree name",
  worktreeNone: "None",
  worktreeProjectFolder: "Project folder",
  chatSettingHint: "Where task chips appear.",
  compactHint: "One line with Open in Tasks.",
  chatSettingTitle: "Task updates in chat",
  showInChat: "Show in chat",
  tasksTabOnly: "Tasks tab only",
  compactChips: "Compact chips",
  fromComputer: "From this computer",
  loading: "Loading tasks…",
  loadError: "Could not load tasks. Try again.",
  kvTask: "Task",
  kvAssistant: "Assistant",
  kvStatus: "Status",
  kvCreated: "Created",
  kvUpdated: "Updated",
} as const;

export const PROJECT_TASK_STATUS_LABEL = {
  queued: PROJECT_PAGE_TASKS_COPY.statusQueued,
  running: PROJECT_PAGE_TASKS_COPY.statusRunning,
  done: PROJECT_PAGE_TASKS_COPY.statusDone,
  failed: PROJECT_PAGE_TASKS_COPY.statusFailed,
  cancelled: PROJECT_PAGE_TASKS_COPY.statusCancelled,
} as const;
