/** EN PASS Tasks tab copy — prefer "assistant"; exact offline EN. */
export const PROJECT_PAGE_TASKS_COPY = {
  tab: "Tasks",
  intro: "Tasks assigned in this project.",
  aria: "Project tasks",
  empty: "No tasks yet",
  emptyAssign: "Assign task",
  filterAllAssistants: "All assistants",
  filterAllStatus: "All status",
  statusQueued: "Queued",
  statusRunning: "Running",
  statusDone: "Done",
  statusFailed: "Failed",
  statusCancelled: "Cancelled",
  offline: "Connection to the project computer was lost.",
  offlineRetry: "Retry",
  planCounts: (used: number, max: number) =>
    `${used} of ${max} tasks this plan`,
  planTip: "Plan limit for task records. Resets monthly.",
  taskInfo: "Task info",
  taskInfoTip: "Cloud keeps title, status and times only.",
  statusTimeline: "Status timeline",
  openHistory: "Open history",
  loadOlder: "Load older",
  openReport: "Open report",
  openTask: "Open task",
  openInTasks: "Open in Tasks",
  backToList: "Back",
  assignTitle: "Assign task",
  assignAssistant: "Assistant",
  assignPrompt: "Task",
  assignSubmit: "Assign",
  assignCancel: "Cancel",
  branch: "Branch",
  worktree: "Worktree",
  createWorktree: "Create worktree",
  chatSettingTitle: "Task updates in chat",
  showInChat: "Show in chat",
  tasksTabOnly: "Tasks tab only",
  compactChips: "Compact chips",
  fromComputer: "From this computer",
  loading: "Loading tasks…",
  loadError: "Could not load tasks. Try again.",
} as const;

export const PROJECT_TASK_STATUS_LABEL = {
  queued: PROJECT_PAGE_TASKS_COPY.statusQueued,
  running: PROJECT_PAGE_TASKS_COPY.statusRunning,
  done: PROJECT_PAGE_TASKS_COPY.statusDone,
  failed: PROJECT_PAGE_TASKS_COPY.statusFailed,
  cancelled: PROJECT_PAGE_TASKS_COPY.statusCancelled,
} as const;
