/** Auxiliary scripts required by ~/.agent-witch/agent-witch.ts (downloaded on every install). */
export const AGENT_WITCH_CLIENT_INSTALL_SCRIPT_NAMES = [
  "resolveAgentWitchLocalLayout.ts",
  "agentWitchConnectionHealth.ts",
  "agentWitchConnectionHealth.constants.ts",
  "readHarnessExportSets.ts",
  "buildWriterCliInvocation.ts",
  "agentWitchRunSessions.ts",
  "agentWitchWriterSession.ts",
  "agentWitchPendingRunSessions.ts",
  "agentWitchRunFinish.ts",
  "ensureHarnessWriterCli.ts",
  "agentWitchLocalRunStore.ts",
  "agentWitchTerminalStreamState.ts",
  "agentWitchShellSession.ts",
  "agentWitchRunSessionsAwaitingInput.ts",
  "agentWitchRunSessionsPty.ts",
  "agentWitchDeviceAuth.constant.ts",
  "resolveAgentWitchAppOriginFromWsUrl.ts",
  "agentWitchCloudApi.ts",
  "agentWitchCloudJobPoll.ts",
  "requestLocalAgentWitchRestart.ts",
  "agentWitchWakeConstants.ts",
  "agentWitchEd25519.ts",
  "agentWitchDeviceKeypair.ts",
  "agentWitchLocalApp.constants.ts",
  "agentWitchLocalTrafficLog.ts",
  "agentWitchLocalRag.ts",
  "agentWitchLocalApp.ts",
  "handleAgentWitchWriterEnsure.ts",
  "dispatch/agentRunInputGuardrails.constant.ts",
  "dispatch/AgentRunStatus.constant.ts",
  "dispatch/DispatchPolicy.constant.ts",
  "dispatch/types/AgentRunRecord.type.ts",
] as const;

export type AgentWitchClientInstallScriptName =
  (typeof AGENT_WITCH_CLIENT_INSTALL_SCRIPT_NAMES)[number];
