import { AGENT_WITCH_MESSAGE_TYPES } from "@/lib/agentWitch/types/AgentWitchMessageType.constant";

const QUEUEABLE_AGENT_WITCH_DISPATCH_MESSAGE_TYPES = new Set<string>([
  AGENT_WITCH_MESSAGE_TYPES.COMMAND_CLAUDE_RUN,
  AGENT_WITCH_MESSAGE_TYPES.HARNESS_REQUEST,
  AGENT_WITCH_MESSAGE_TYPES.AUTOMATIONS_SYNC,
  AGENT_WITCH_MESSAGE_TYPES.AUTOMATIONS_RUN,
  AGENT_WITCH_MESSAGE_TYPES.PROJECT_MESSAGE_HISTORY,
  AGENT_WITCH_MESSAGE_TYPES.SYNC_AVAILABLE,
  AGENT_WITCH_MESSAGE_TYPES.SYNC_PURGE,
]);

export const isQueueableAgentWitchDispatchMessageType = (
  messageType: string,
): boolean => QUEUEABLE_AGENT_WITCH_DISPATCH_MESSAGE_TYPES.has(messageType);
