/**
 * Product EN lock — docs/design/activity-restore/COPY.md (2026-10-06).
 * Locked keys reused from PROJECT_DELIVERY_MODE_ACTIVITY_COPY / activity.auto_*.
 */
export const ACCESS_LOG_COPY = {
  title: "Access log",
  /** Members-rail quiet link (HN-H3 project-library design). */
  railLink: "View access log",
  ariaLabel: "Access log: changes to who can use this project",
  intro:
    "Who joined, left, or was invited, and how each assistant gets messages. Only you can see this.",
  retention:
    "Shows the last {maxEvents} changes from the past {maxAgeDays} days.",
  empty: "No changes yet. Invites, approvals, and removals show up here.",
  emptyFiltered: "No changes of this kind yet.",
  loading: "Loading the Access log…",
  loadMore: "Show older",
  loadingMore: "Loading…",
  end: "That's everything in the log.",
  error: "Couldn't load the Access log.",
  errorMore: "Couldn't load older changes.",
  retry: "Try again",
  ownerOnly: "Only the project owner can see the Access log.",
  filterLabel: "Show",
  filterAll: "All",
  filterAccess: "People and invites",
  filterWake: "How assistants get messages",
  filterSafety: "Safety rules",
  actorYou: "You",
  nameFallbackAssistant: "this assistant",
  nameFallbackPerson: "this person",
  nameFallbackComputer: "this computer",
  nameFallbackUnknown: "someone",
  inviteCreated: "You created an assistant invite",
  inviteRevoked: "You revoked an assistant invite",
  autoOn: "You turned on auto-approve for an invite",
  autoOff: "You turned off auto-approve for an invite",
  joinedAuto: "{name} joined with an invite you auto-approved",
  requestApproved: "You approved {name}",
  requestDenied: "You denied a request to join from {name}",
  requestDeniedNoName: "You denied a request to join",
  memberRemoved: "You removed {name} from the project",
  memberLeft: "{name} left the project",
  humanInviteCreated: "You invited a person as a {roleLabel}",
  humanInviteCreatedNoRole: "You invited a person",
  humanInviteRevoked: "You revoked an invite to join as a {roleLabel}",
  humanInviteRevokedNoRole: "You revoked an invite for a person",
  humanInviteAccepted: "{name} joined as a {roleLabel}",
  modeAutoWake: "{name} now wakes up on its own",
  // S0-2 draft EN (pending Product copy lock).
  runsWithoutApprovalOn:
    "You allowed tasks to run on this project's computer without approval",
  runsWithoutApprovalOff:
    "You turned approval back on for tasks on this project's computer",
  // DF-038 draft EN (pending Product copy lock): bot-made invites.
  botInviteCreated: "Invited by {bot}: an assistant invite was created",
  botInviteJoined: "{name} joined. Invited by {bot}",
  ruleDropped: 'You dropped the safety rule "{title}".',
  ruleDroppedNoTitle: "You dropped a safety rule.",
  ruleRestored: 'You restored the safety rule "{title}".',
  ruleRestoredNoTitle: "You restored a safety rule.",
  detailInvite: "Invite {inviteLabel}",
  detailExpires: "Expires {date}",
  detailKindBot: "Assistant",
  detailKindHuman: "Person",
  detailKindComputer: "Computer",
  detailModeWas: "Was: {mode}",
  detailWakeLinkSaved: "A wake link was saved.",
  timeJustNow: "Just now",
  timeMinutes: "{n} min ago",
  timeHours: "{n} hr ago",
} as const;
