export {
  WORKFLOW_BUILDER_ABOUT_SECTION,
  WORKFLOW_BUILDER_QUESTIONS_SECTION,
  WORKFLOW_BUILDER_STEPS_SECTION,
  WORKFLOW_BUILDER_FLOW_SECTION,
  WORKFLOW_BUILDER_INSTRUCTIONS_LABEL,
  WORKFLOW_BUILDER_INSTRUCTIONS_PLACEHOLDER,
} from "../workflowBuilderCopy.constant";
